# Generated by Django 6.1.1 on 2026-09-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are kept for history but excluded from selection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'province',
                'verbose_name_plural': 'provinces',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='locations.province')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='locations.city')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='locations.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='locations.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='locations.region')),
            ],
            options={
                'verbose_name': 'location alias',
                'verbose_name_plural': 'location aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SourceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('divar', 'Divar'), ('sheypoor', 'Sheypoor')], max_length=32)),
                ('external_id', models.CharField(max_length=191)),
                ('raw_label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_locations', to='locations.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_locations', to='locations.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_locations', to='locations.region')),
            ],
            options={
                'verbose_name': 'source location mapping',
                'verbose_name_plural': 'source location mappings',
                'ordering': ['source', 'external_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'code'), name='city_unique_code_per_province'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('city', 'code'), name='region_unique_code_per_city'),
        ),
        migrations.AddConstraint(
            model_name='locationalias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', True), ('province__isnull', False), ('region__isnull', True)), models.Q(('city__isnull', False), ('province__isnull', True), ('region__isnull', True)), models.Q(('city__isnull', True), ('province__isnull', True), ('region__isnull', False)), _connector='OR'), name='location_alias_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='sourcelocation',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='source_location_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='sourcelocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', True), ('province__isnull', False), ('region__isnull', True)), models.Q(('city__isnull', False), ('province__isnull', True), ('region__isnull', True)), models.Q(('city__isnull', True), ('province__isnull', True), ('region__isnull', False)), _connector='OR'), name='source_location_exactly_one_target'),
        ),
    ]
