# Generated by Django 6.1.1 on 2026-09-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('divar', 'Divar'), ('sheypoor', 'Sheypoor')], max_length=32)),
                ('source_id', models.CharField(max_length=191)),
                ('source_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale / purchase'), ('rent', 'Rent')], max_length=16)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('garden', 'Garden'), ('rural_house', 'Rural house'), ('commercial', 'Commercial / shop'), ('other', 'Other')], default='other', max_length=32)),
                ('raw_location', models.CharField(blank=True, default='', help_text='Location text as published by the source, before normalization.', max_length=255)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, help_text='Total price for sale listings, in Toman.', max_digits=16, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, help_text='Deposit (ودیعه) for rent listings, in Toman.', max_digits=16, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=0, help_text='Monthly rent (اجاره ماهانه) for rent listings, in Toman.', max_digits=16, null=True)),
                ('price_currency', models.CharField(choices=[('IRT', 'Iranian Toman'), ('IRR', 'Iranian Rial')], default='IRT', max_length=3)),
                ('is_price_negotiable', models.BooleanField(default=False, help_text='Source published a negotiable/unspecified price (توافقی).')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Not seen in a recent crawl'), ('delisted', 'Removed or disabled at the source'), ('hidden', 'Hidden locally')], default='active', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication time reported by the source.', null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Last payload received from the source, kept for diagnostics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.region')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['-first_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'listing image',
                'verbose_name_plural': 'listing images',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('active', 'Active'), ('stale', 'Not seen in a recent crawl'), ('delisted', 'Removed or disabled at the source'), ('hidden', 'Hidden locally')], default='', max_length=16)),
                ('to_status', models.CharField(choices=[('active', 'Active'), ('stale', 'Not seen in a recent crawl'), ('delisted', 'Removed or disabled at the source'), ('hidden', 'Hidden locally')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='listings.listing')),
            ],
            options={
                'verbose_name': 'listing status event',
                'verbose_name_plural': 'listing status events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['source', 'status'], name='listing_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'status'], name='listing_city_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['transaction_type', 'property_type'], name='listing_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-published_at'], name='listing_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='listing_unique_source_identity'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), models.Q(('deposit__isnull', True), ('deposit__gte', 0), _connector='OR'), models.Q(('monthly_rent__isnull', True), ('monthly_rent__gte', 0), _connector='OR'), models.Q(('area_sqm__isnull', True), ('area_sqm__gte', 0), _connector='OR')), name='listing_no_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(fields=('listing', 'position'), name='listing_image_unique_position'),
        ),
    ]
