# Generated by Django 6.1.1 on 2026-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale / purchase'), ('rent', 'Rent'), ('unspecified', 'Not stated by the source')], max_length=16),
        ),
    ]
