# Generated by Django 6.1.1 on 2026-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='consecutive_misses',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sweeps in a row that did not see this listing at the source.'),
        ),
    ]
