# Generated by Django 6.1.1 on 2026-09-17 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_consecutive_misses'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Reviewed duplicate of this listing. Metadata only: neither row is merged, rewritten or deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='listings.listing'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('duplicate_of', models.F('id')), _negated=True), name='listing_not_its_own_duplicate'),
        ),
    ]
