# Generated by Django 6.1.1 on 2026-09-17 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('divar', 'Divar'), ('sheypoor', 'Sheypoor')], max_length=32)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale / purchase'), ('rent', 'Rent'), ('unspecified', 'Not stated by the source')], default='unspecified', max_length=16)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('garden', 'Garden'), ('rural_house', 'Rural house'), ('commercial', 'Commercial / shop'), ('other', 'Other')], default='other', max_length=32)),
                ('source_external_id', models.CharField(blank=True, default='', max_length=191)),
                ('source_category', models.CharField(blank=True, default='', max_length=191)),
                ('page_limit', models.PositiveSmallIntegerField(blank=True, help_text='Maximum list pages to fetch; NULL means until the source runs out.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued for a worker'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partially_succeeded', 'Partially succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('report', models.JSONField(blank=True, default=dict, help_text='Final counters and aggregated failures for this run.')),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('stubs_seen', models.PositiveIntegerField(default=0)),
                ('details_fetched', models.PositiveIntegerField(default=0)),
                ('listings_created', models.PositiveIntegerField(default=0)),
                ('listings_updated', models.PositiveIntegerField(default=0)),
                ('listings_skipped', models.PositiveIntegerField(default=0)),
                ('listings_out_of_scope', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.region')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'crawl job',
                'verbose_name_plural': 'crawl jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('queued', 'Queued for a worker'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partially_succeeded', 'Partially succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=24)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued for a worker'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partially_succeeded', 'Partially succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=24)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crawling.crawljob')),
            ],
            options={
                'verbose_name': 'crawl job event',
                'verbose_name_plural': 'crawl job events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrawlSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('divar', 'Divar'), ('sheypoor', 'Sheypoor')], max_length=32)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale / purchase'), ('rent', 'Rent'), ('unspecified', 'Not stated by the source')], default='unspecified', max_length=16)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('garden', 'Garden'), ('rural_house', 'Rural house'), ('commercial', 'Commercial / shop'), ('other', 'Other')], default='other', max_length=32)),
                ('source_external_id', models.CharField(blank=True, default='', max_length=191)),
                ('source_category', models.CharField(blank=True, default='', max_length=191)),
                ('page_limit', models.PositiveSmallIntegerField(blank=True, help_text='Maximum list pages to fetch; NULL means until the source runs out.', null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('interval_minutes', models.PositiveIntegerField(default=360)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='NULL means due as soon as it is enabled.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.city')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_scope', to='locations.region')),
            ],
            options={
                'verbose_name': 'crawl schedule',
                'verbose_name_plural': 'crawl schedules',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['status', 'created_at'], name='crawl_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['source', 'status'], name='crawl_job_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawljob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', True), ('province__isnull', False), ('region__isnull', True)), models.Q(('city__isnull', False), ('province__isnull', True), ('region__isnull', True)), models.Q(('city__isnull', True), ('province__isnull', True), ('region__isnull', False)), _connector='OR'), name='crawl_job_scope_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='crawlschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('city__isnull', True), ('province__isnull', False), ('region__isnull', True)), models.Q(('city__isnull', False), ('province__isnull', True), ('region__isnull', True)), models.Q(('city__isnull', True), ('province__isnull', True), ('region__isnull', False)), _connector='OR'), name='crawl_schedule_scope_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='crawlschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_minutes__gte', 1)), name='crawl_schedule_interval_positive'),
        ),
    ]
