# Generated by Django 6.1.1 on 2026-09-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='swept_at',
            field=models.DateTimeField(blank=True, help_text='When the listing lifecycle sweep processed this run (idempotency).', null=True),
        ),
    ]
