# Generated by Django 6.1.1 on 2026-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('divar', 'Divar'), ('sheypoor', 'Sheypoor')], max_length=32)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale / purchase'), ('rent', 'Rent'), ('unspecified', 'Not stated by the source')], max_length=16)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('garden', 'Garden'), ('rural_house', 'Rural house'), ('commercial', 'Commercial / shop'), ('other', 'Other')], max_length=32)),
                ('external_id', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'source category',
                'verbose_name_plural': 'source categories',
                'ordering': ['source', 'transaction_type', 'property_type'],
                'constraints': [models.UniqueConstraint(fields=('source', 'transaction_type', 'property_type'), name='source_category_unique_mapping')],
            },
        ),
    ]
