# Generated by Django 6.1.1 on 2026-09-17 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_listing_consecutive_misses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('confirmed', 'Confirmed duplicate'), ('rejected', 'Rejected by a reviewer')], default='pending', max_length=16)),
                ('canonical', models.CharField(blank=True, choices=[('left', 'Keep the first listing'), ('right', 'Keep the second listing')], help_text='Which side a reviewer decided to keep (confirmed candidates only).', max_length=8, null=True)),
                ('score', models.PositiveSmallIntegerField(help_text='Weighted evidence at detection time, 0-100.')),
                ('signals', models.JSONField(blank=True, default=list, help_text='The individual signals that produced the score.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_as_left', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reviews', to=settings.AUTH_USER_MODEL)),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_as_right', to='listings.listing')),
            ],
            options={
                'verbose_name': 'duplicate candidate',
                'verbose_name_plural': 'duplicate candidates',
                'ordering': ['-score', '-id'],
                'indexes': [models.Index(fields=['status', '-score'], name='dedup_status_score_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('left__lt', models.F('right'))), name='duplicate_candidate_ordered_pair'), models.UniqueConstraint(fields=('left', 'right'), name='duplicate_candidate_unique_pair')],
            },
        ),
    ]
